### ISSUE TITLE
修改事务：友谊之舟联盟社团自述页面需要更新

### ISSUE THREAD

**Issue by StarsetNight** [StarsetNight/Friend-Docs#4]
友谊之舟联盟社团作为服务器内的大型玩家社团，需要撰写一个更为详细的社团自述。

**Comment by StarsetNight** [comment]
# 不是哥们太神金了吧

> 参见提交 c5314f9ec00f8f665a16f2e7ad531cfad77ef612

接下来该写内部页面了吧，还有外部页面太神金了，我喜欢，再神金一点（）

**Comment by chengyza** [comment]
好好好
