### ISSUE TITLE
待办事务：蘑菇岛社团介绍栏

### ISSUE THREAD

**Issue by StarsetNight** [StarsetNight/Friend-Docs#5]

**Comment by ohkl** [comment]
(music 天气之子) 帮忙加上
蘑菇岛 蘑菇岛是一个休闲养老社团 由我们社长_**yoturn带领**_ 成立于2024年 我们**### 团结 摸鱼**  我们专注于**### 建筑** 生电  _蘑菇🍄养殖业_   适合加入的人有：生电面包人 **### _养老玩家_** 建筑大师等 咸鱼玩家 等 欢迎各位面包人 猫娘们的加入（🤭）by 重新速配的二十八
2024年暑假
